@echo off
mkdir "credit-risk-model"
cd "credit-risk-model"
mkdir ".github"
mkdir ".github\workflows"
mkdir "data"
mkdir "data\raw"
mkdir "data\processed"
mkdir "notebooks"
mkdir "src"
mkdir "src\api"
mkdir "tests"
type nul > ".github\workflows\ci.yml"
type nul > "notebooks\1.0-eda.ipynb"
type nul > "src\__init__.py"
type nul > "src\data_processing.py"
type nul > "src\train.py"
type nul > "src\predict.py"
type nul > "src\api\main.py"
type nul > "src\api\pydantic_models.py"
type nul > "tests\test_data_processing.py"
type nul > "Dockerfile"
type nul > "docker-compose.yml"
type nul > "requirements.txt"
type nul > ".gitignore"
type nul > "README.md"
type nul > "GEMINI.md"

